name: Release (svc)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

env:
  IMAGE: hontech/smf-training-tracker

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - name: Configure git identity (if Nx commits/tags)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Docker Hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Run your Nx release script, but force production scheme + auto-yes
      - name: Run Nx release (Docker, production)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release:svc -- --dockerVersionScheme=production --yes

      - name: Read Nx image tag
        id: nx
        run: |
          TAG=$(node -p "require('./dist/.nx-release.json').versionTag")
          if [ -z "$TAG" ]; then
            echo "Nx release tag not found in dist/.nx-release.json"; exit 1
          fi
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"

      - name: Tag & push :latest
        run: |
          IMAGE="${{ env.IMAGE }}"
          TAG="${{ steps.nx.outputs.tag }}"
          docker pull "$IMAGE:$TAG" || true
          docker tag "$IMAGE:$TAG" "$IMAGE:latest"
          docker push "$IMAGE:latest"
